const express=require("express")
const { tenderCreation, archiveTender, retrieveTender, viewTender, corrigendumTender, getTenderNo, viewPdf, downloadPdf } = require("../controllers/tender")
const { tenderpdf } = require("../middleware/faculty")
const router = express.Router()
router.post('/create',tenderpdf,tenderCreation)
router.post('/archive',archiveTender)
router.post('/retrieve',retrieveTender)
router.get('/view',viewTender)
router.post('/corrigendum',tenderpdf,corrigendumTender)
router.get('/refNo',getTenderNo)
router.get('/vpdf/:id',viewPdf)
router.get('/dpdf/:id',downloadPdf)
module.exports=router