const express=require('express')
const { viewContact } = require('../controllers/ContactController')
const { createFacultyMembership, assignSubjects, createFaculty } = require('./create')
const { viewStudents, viewAllStudents, viewFaculty, viewAllDetailsFaculty, organizationFilter, viewFacultyName, viewFacultyMembersWithFaculty, viewCourseByFaculty } = require('./view')
const { loginAccess, activeInactive, updateScheduling } = require('./edit')
const { deleteSchedulingCourse } = require('./delete')
const router=express.Router()

router.get('/studentsView',viewAllStudents)
router.get('/facultyView',viewFaculty)
router.post('/subassign',assignSubjects)
router.get('/contactview',viewContact)
router.get('/organizationfilter',organizationFilter)
router.post('/faculty_create',createFaculty)
router.get('/faculty_show',viewFacultyName)
router.patch('/access',loginAccess)
router.patch('/act_inact_faculty',activeInactive)
router.get('/faculty_member_faculty/:faculty',viewFacultyMembersWithFaculty)
router.get('/delete/:status/:batch/:courseID',deleteSchedulingCourse)
router.patch('/updateSchedule',updateScheduling)
router.get('/course_faculty/:faculty',viewCourseByFaculty)
module.exports=router